name: deploy-py-lambda-report_put

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/report_put/**'
jobs:
  call-workflow-config-repo:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      directory: report_put